// src/ui/src/app/game-log/game-log.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-game-log',
  templateUrl: './game-log.component.html',
  styleUrls: ['./game-log.component.scss']
})
export class GameLogComponent {
  @Input() logs!: string[]

  ngOnChanges(){
    setTimeout(()=>{
      const gameLogTextarea = document.getElementById('game-log')
      gameLogTextarea?.scroll({behavior: 'smooth', top: gameLogTextarea?.scrollHeight})
    }, 50)
  }
}

<label for="game-log">Game log</label>
<textarea id="game-log" readonly cols="30" rows="10" style="height: 500px;">{{logs.join('\n')}}</textarea>

// ui/src/pages/game/components/GameLog.tsx
import { useMemo } from 'react';
import TextField from '@mui/material/TextField';

export interface GameLogProps {
  logs: string[];
}

export default function GameLog({ logs }: GameLogProps) {
  useMemo(() => {
    const logContainer = document.querySelector('.log-container textarea');
    if (logContainer) {
      logContainer.scrollTo({ behavior: 'smooth', top: logContainer.scrollHeight });
    }
  }, [logs]);

  return (
    <TextField
      value={logs.join('\n')}
      multiline
      rows={28}
      slotProps={{ input: { readOnly: true } }}
      className="log-container"
      fullWidth
      variant="outlined"
      sx={{
        padding: '16px',
        borderRadius: '8px',
      }}
    />
  );
}
